#version: '3.9'

services:
  node-api:
    image: ghcr.io/anouvene/cicd-projet-docker/node-api:latest
    pull_policy: always
    environment:
      - NODE_ENV=production
    ports:
      - "3001:80"
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  frontend:
    image: ghcr.io/anouvene/cicd-projet-docker/frontend:latest
    pull_policy: always
    ports:
      - 8888:80 # Port exposé sur le serveur (évite conflit avec port 80):Port exposé dans le container
    restart: always