version: '3.9'
services:
  node-api:
    image: ghcr.io/anouvene/cicd-projet-docker/node-api:latest
    ports:
      - '3000:80'
  frontend:
    image: ghcr.io/anouvene/cicd-projet-docker/frontend:latest
    ports:
      - '8888:80'
  cypress:
    image: cypress/included
    working_dir: /e2e
    volumes:
      - ./frontend:/e2e
    entrypoint: cypress run --config baseUrl=http://frontend/realisations/cicd-docker/ --headless --browser chrome -C cypress.headless.config.js
    depends_on:
      - frontend
      - node-api