name: CI/CD avec images Docker et Docker Compose

env:
  SERVER_USER: "anouvene"
  #SERVER_STAGING: "78.138.45.88"
  SERVER_PRODUCTION: "151.80.59.182"


concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  tests_frontend: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
    - name: checkout le code
      uses: actions/checkout@v4

    - name: installer Node.js
      uses: actions/setup-node@v3 
      with:
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: installer les dépendances
      run: npm ci --prefer-offline

    - name: Exécuter les tests
      run: npm run test:coverage

    - name: vérifie les vulnérabilités
      run: npm audit --audit-level=moderate
    - name: vérifie le code
      run: npm run lint

    - name: Upload du rapport de couverture sur Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  tests_backend:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: node-api
    steps:
    - name: Checkout le code
      uses: actions/checkout@v4

    - name: Installer Node.js
      uses: actions/setup-node@v3 
      with:
        cache: 'npm'
        cache-dependency-path: node-api/package-lock.json

    - name: Installer les dépendances
      run: npm ci --prefer-offline
          
    - name: Exécuter les tests
      run: npm run test:ci
          
    - name: Vérifier le code
      run: npm run lint
          
    - name: Vérifier les vulnérabilités
      run: |
        npm audit --audit-level=moderate

    - name: Upload du rapport de couverture sur Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build:
    needs: [tests_frontend, tests_backend]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        include:
          - path: 'frontend'
            full_image_name: ghcr.io/${{ github.repository }}/frontend
          - path: 'node-api'
            full_image_name: ghcr.io/${{ github.repository }}/node-api
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Mise en place de Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login sur GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Récupération des métadonnées
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.full_image_name }}

      - name: Build et push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ matrix.full_image_name }}:latest
          context: ./${{ matrix.path }}
          platforms: linux/amd64       # ✅ Important pour compatibilité serveur VPS
          no-cache: true               # ✅ Forcer rebuild complet pour que VITE_BASE soit pris en compte
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VITE_BASE=/realisations/cicd-docker/
      
      - name: Build frontend pour les tests # Image pour test e2e avec Cypress (voir docker-compose)
        if: matrix.path == 'frontend'
        working-directory: ./frontend
        run: |
          docker build \
            --build-arg VITE_BASE=/ \
            -t ghcr.io/anouvene/cicd-projet-docker/frontend:e2e \
            -f Dockerfile .
          docker push ghcr.io/anouvene/cicd-projet-docker/frontend:e2e

  e2e:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login sur GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lancement des tests E2E
        run: docker compose up --exit-code-from cypress --abort-on-container-exit
      - name: Nettoyage
        run: docker compose down -v --remove-orphans

  # deploy_staging:
  #   needs: [e2e]
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: staging
  #   steps:
  #   - name: checkout le code
  #     uses: actions/checkout@v4
  #   - name: déployer
  #     uses: ./.github/actions/deploy
  #     with:
  #       server_ip: ${{ env.SERVER_STAGING }}
  #       secret_key: ${{ secrets.OVH_STAGING_PKEY }}
  #       token_github: ${{ secrets.GITHUB_TOKEN }}
  
  deploy_production:
    runs-on: ubuntu-latest
    needs: e2e
    environment:
      name: production
    steps:
    - name: Checkout le code
      uses: actions/checkout@v4
    - name: Déploiement
      uses: ./.github/actions/deploy # Action personnalisée
      with:
        server_user: ${{ env.SERVER_USER}}
        server_ip: ${{ env.SERVER_PRODUCTION }}
        secret_key: ${{ secrets.OVH_PROD_PKEY }}
        token_github: ${{ secrets.GITHUB_TOKEN }}
